# model selection ####

# suppose we have data from an experiment like this:
# mean RT correct = 250ms
# mean RT incorrect = 246ms
# accuracy = 0.80

# try to fit this data with both models by adjusting the parameters of the model
# HINT: you can speed up your parameter search by using a small number of samples
# initially, and then increasing the samples as you get closer to a viable set
# of parameters.
# 2nd HINT: Don't adjust the sdrw parameter of the random.walk.model or the criterion
# paramter of the accumulator model.

# You don't need to get a perfect match. Just get in the ballpark. 

#the line below is from the answer to ensure steady output from the code
set.seed(12604) # to `ensure that you see the same results that I did!


#I used drift = 0.015 and crit = 4.8, which did not produce the RTs as required(they are roughly around 240 and 260). Therefore, I switched the 
# parameters to 0.012 and 4.8, with a sdrw = 0.3, the radom walk model produces a correct RT of 254 and an incorrect RT of 244 with a accuracy of 80.2%.
rw.model.result <- random.walk.model(1000, drift=0.012, sdrw=0.3, criterion = 4.8)
rw.model.result %>% group_by(correct) %>% summarize(mean.rt = mean(rt))
mean(rw.model.result$correct)

# I used rate.1 = 86 and rate.2 = 91 with criterion = 3, which produces a inccorect RT of 260 and correct RT of 254 with an accuracy of 78.6%. By switching to 
# a rate.1 = 85 and rate.2 = 91 with criterion = 3, the accumulator model produces an incorrect RT of 259 and a crreoct RT of 252 with an accuracy of 79.1%, which 
# is close to the ideal fitting.
acc.model.result <- accumulator.model(1000, rate.1 = 85, rate.2 = 91, criterion=3)
acc.model.result %>% group_by(correct) %>% summarize(mean.rt = mean(rt))
mean(acc.model.result$correct)


# Can both models do a reasonable job of accounting for the mean RT and accuracy? Report the
# results of your efforts:

# For the random walk model, with a drist = 0.015 and criterion = 4.8 with sdrw = 0.3, the model produces an incorrect RT of 264 and a correct RT of 255 with
# with an accuracy of 77%. For the accumulator model, with a rate.1 = 86 and rate.2 = 91 with criterion = 3, the model produces an incorrect RT of 260 and correct
# RT of 254 with an accuracy of 78.6%. With the expecting output being RT correct = 250 and RT incorect being 246 with an accuracy of 80%, the random walk model and
# the accumulator model appear to be eqaully capable of fitting the model with no further adjustment to the parameters.

# Using the parameters that you found above, plot histograms of the distribution of RTs
# predicted by each model. Based on these distributions, what kind of information could
# we use to evaluate which model is a better descriptor of the data for the experiment?
# Describe briefly how you might make this evaluation.


layout(matrix(1:4, nrow=2, byrow=T))
hist((rw.model.result %>% filter(correct==TRUE))$rt, breaks=seq(0,2000,100), main="RW Model, correct", xlab="RT")
hist((rw.model.result %>% filter(correct==FALSE))$rt, breaks=seq(0,2000,100), main="RW Model, incorrect", xlab="RT")
hist((acc.model.result %>% filter(correct==TRUE))$rt, breaks=seq(0,2000,10), main="ACC Model, correct", xlab="RT")
hist((acc.model.result %>% filter(correct==FALSE))$rt, breaks=seq(0,2000,10), main="ACC Model, incorrect", xlab="RT")

#from the histograms, we can see that the random walk model has a really skewed distribuition whereas the
# accumulator model has a relatively symmetrical distribution and on the other hand, the variability is much
# higher in the random wlak model. Becuase the histograms of the random wal kmodel and the accumulator model 
# are very different, we could compare the histograms from these model to the histogram generated by the real
# data and select the model that generates the histogram that is more similar to the real data.